### ISSUE TITLE
NullReferenceException int the 3.3.1 and 3.3.2

### ISSUE THREAD

**Issue by EhRom** [FlorianHockmann/Gremlin.Net#14]
Hi,

Since I updated to the 3.3.1 and 3.3.2 of the Nuget package, there is a Null Reference Exception. 

Here is the stack trace : 

```cs
   at Gremlin.Net.Driver.Connection.<ReceiveAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.Connection.<SubmitAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.ProxyConnection.<SubmitAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.GremlinClient.<SubmitAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.GremlinClientExtensions.<SubmitAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PartitionedGraph.Program.<ExecuteGremlinServerQueryAsync>d__3.MoveNext()
```

And the code sample:
```cs
string query = "g.V().drop()";

GremlinServer server = new GremlinServer(gremlinServerEndPoint, serverPort, true, $"/dbs/{databaseId}/colls/{collectionId}", primaryKey);
                
using (GremlinClient client = new GremlinClient(server))
{
    IEnumerable<dynamic> results = await GremlinClientExtensions.SubmitAsync<dynamic>(client, requestScript: query);

    foreach (dynamic result in results)
    {
        Console.WriteLine(result.ToString());
    }
}
```

I know this is not the right version project, but I can not find the original repository for the Nuget package.

This is not blocking, since I can use the 3.2.8 version of the NuGet pacakge.

Thanks in advance.

**Comment by FlorianHockmann** [comment]
Hi @EhRom, the right repo is the one from Apache TinkerPop: https://github.com/apache/tinkerpop. It contains the source code for Gremlin.Net in the directory `gremlin-dotnet`.
The issue tracker for TinkerPop is here: https://issues.apache.org/jira/projects/TINKERPOP/issues

It looks like you're using Cosmos DB which doesn't support GraphSON 3 yet as far as I know. That's probably the reason why it works with version 3.2.8, but now with 3.3.2 as GraphSON 3 is used by default in TinkerPop 3.3.z, whereas GraphSON 2 was used in versions 3.2.z.

You can check if that's actually the case by creating the `GremlinClient` with Gremlin.Net 3.3.2 like this:
```cs
var client = new GremlinClient(server, new GraphSON2Reader(),
        new GraphSON2Writer(), GremlinClient.GraphSON2MimeType));
```

**Comment by fujiy** [comment]
@FlorianHockmann, I have the same problem. I'm already using GraphSON 2

`using (var gremlinClient = new GremlinClient(gremlinServer, new GraphSON2Reader(), new GraphSON2Writer(), GremlinClient.GraphSON2MimeType))`

**Comment by EhRom** [comment]
Hi Florian,
Very clear answer. Thank you very much. Specifying the reader and writer works fine.
