### ISSUE TITLE
NullReferenceException int the 3.3.4

### ISSUE THREAD

**Issue by torkilPe** [FlorianHockmann/Gremlin.Net#17]
Hi 

I have recently moved to Gremlin.net 3.3.4

I am using the concept 

            string gremlinDatabasePath = $"/dbs/{databaseName}/colls/{collectionName}";

            var _server = new GremlinServer(gremlinEndPoint,
                                            port,
                                            enableSsl,
                                            gremlinDatabasePath,
                                            gremlinAuthKey);

          where the gremlinEndPoint is taken from the azure portal and the https:// has been removed

            var client = new GremlinClient(_server,
                                           new GraphSON2Reader(),
                                           new GraphSON2Writer(),
                                           GremlinClient.GraphSON2MimeType);

what causes this exception thatcomes up. I left the Azure.Document.Graph preview API so I have to get it to worlk

Stack StackTrace :    at Gremlin.Net.Structure.IO.GraphSON.GraphSONWriter.WriteObject(Object objectData)
   at Gremlin.Net.Driver.Connection.<SendAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.Connection.<SubmitAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.ProxyConnection.<SubmitAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.GremlinClient.<SubmitAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gremlin.Net.Driver.GremlinClientExtensions.<SubmitAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDT.MYA.GraphDataAccess.GremlinExecuter.GremlinCommandExecuter.<ExecuteGremlinCommands>d__0.MoveNext() in D:\projects\CPH.EA.MYA\Trunk\Projects\MDT.Manar.Graph.DataAccess\GremlinExecuter\GremlinCommandExecuter.cs:line 39

**Comment by FlorianHockmann** [comment]
Please read the [README.md](https://github.com/FlorianHockmann/Gremlin.Net/blob/master/README.md). It should not only make clear that this is not the right repository, but also provide pointers to where you can actually report problems with Gremlin.Net.

Your description here is very incomplete, so it's basically impossible to find the problem. The stack trace hints at a problem with GraphSON serialization, but you don't show any information of what you're trying to send to the server.
If you aren't sure how to use Gremlin.Net correctly, then please ask on [gremlin-users](https://groups.google.com/forum/#!forum/gremlin-users). If the problem is specific to Cosmos DB, then please ask their support.

**Comment by torkilPe** [comment]
Hi Florian

Sorry for that.

BR
Torkil
